// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using resqdoc2.Models;

#nullable disable

namespace resqdoc2.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("resqdoc2.Models.Cobrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cod")
                        .HasColumnType("integer")
                        .HasColumnName("Cod");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Cobrade");
                });

            modelBuilder.Entity("resqdoc2.Models.ResqDoc.Models.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CobradeId")
                        .HasColumnType("integer")
                        .HasColumnName("CobradeId");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("Data");

                    b.Property<int>("Gravidade")
                        .HasColumnType("integer")
                        .HasColumnName("Gravidade");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Título");

                    b.HasKey("Id");

                    b.HasIndex("CobradeId");

                    b.ToTable("OcorrenciaTabela");
                });

            modelBuilder.Entity("resqdoc2.Models.ResqDoc.Models.Ocorrencia", b =>
                {
                    b.HasOne("resqdoc2.Models.Cobrade", "Cobrade")
                        .WithMany()
                        .HasForeignKey("CobradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobrade");
                });
#pragma warning restore 612, 618
        }
    }
}
